### ISSUE TITLE
Investigate the plateauing reward

### ISSUE THREAD

**Issue by IsaacWolverton** [mit-quest/nuclear-core-design#8]
Vary the exploration fraction in rllib to try and eliminate the plateau.

**Comment by IsaacWolverton** [comment]
This could be the cause: [](https://arxiv.org/pdf/1904.11455.pdf)

**Comment by Josh-Joseph** [comment]
Interesting. Nice find! Yeah I think this is a great articulation of what might be up here. It's interesting it's made worse as num_workers is increased (and doesn't even appear when num_workers=0?).

This makes me think that I wonder if we just tuned the rewards a bit more we'd see this behavior change.

They also offer this bit that we could try a few directions of:
> There are essentially three approaches: reduce interference, reduce coupling, or tackle ray interfere head-on.

My intuition is that reducing coupling may be the easiest here.

**Comment by IsaacWolverton** [comment]
Things that didn’t work:
- Enabling noisy DQN
- Disabling dueling or double DQN
- Varying the exploration fraction
- Switching to AC2 
- Switching to PPO (in fact this may have made it worse)
  - Sharing weights between the policy and value network

Here is the chart of mean reward when varying the DQN exploration fraction. 
![ray_tune_episode_reward_mean](https://user-images.githubusercontent.com/31489037/70154783-0f34d600-167f-11ea-8252-ad030f7f6c67.png)

Here are the corresponding exploration values:
![ray_tune_info_max_exploration](https://user-images.githubusercontent.com/31489037/70154804-1f4cb580-167f-11ea-9b9c-885f01a4ce8b.png)
All epsilon values start at 1 and are annealed to 0.02 over some fraction of 100,000 timesteps. The fractions used in this run were: [.001, .01, .1, .2, .3, .4, .5]. The orange line corresponds to the .001 fraction and the green line corresponds to the .5 fraction. Unfortunately there is no clear correlation between exploration fraction and eliminating the plateau.

**Comment by Josh-Joseph** [comment]
I'm guessing these were also just for 1 run each? my first past intuition here is the noise from the randomness is larger than the performance differences between the fraction values

**Comment by IsaacWolverton** [comment]
We've decided that this is not an issue with rllib but rather just a general difficulty brought about by reinforcement learning.
