### ISSUE TITLE
Investigate why increasing num_workers slows down training

### ISSUE THREAD

**Issue by IsaacWolverton** [mit-quest/nuclear-core-design#9]
Compare the reward graphs of the coloring env to other environments when num_workers is increased. Also try varying the number of samples per batch and other parameters that effect the batch update/ rollout process.

**Comment by IsaacWolverton** [comment]
Below are graphs of two algorithms (PPO and DQN) on the coloring environment and CartPole. All parameters were left at their default except num_workers. The y-axis is always mean reward and the x-axis is always wall time.

CartPole - PPO
![cartpole_ppo_episode_reward_mean](https://user-images.githubusercontent.com/31489037/70150830-a4809c00-1678-11ea-8bce-110cdf382db8.png)
Num_workers: orange=3, blue=2, light_blue=1, red=0

CartPole - DQN
![cartpole_dqn_episode_reward_mean](https://user-images.githubusercontent.com/31489037/70151096-1b1d9980-1679-11ea-93e1-da8817166909.png)
Num_workers: blue=3, red=2, light_blue=1, orange=0

Coloring - DQN
![coloring_dqn_episode_reward_mean](https://user-images.githubusercontent.com/31489037/70151215-42746680-1679-11ea-96c4-5e5c6af147b5.png)
Num_workers: blue=3, red=2, light_blue=1, orange=0

Coloring - PPO
![coloring_ppo_episode_reward_mean](https://user-images.githubusercontent.com/31489037/70151507-b151bf80-1679-11ea-8e34-52a5e817530e.png)
Num_workers: blue=3, orange=2, light_blue=1, red=0

Note that an increasing number of workers causes training to speed up for both DQN and PPO on CartPole. The same does not hold true however for the coloring environment. In the DQN case, there is no correlation between num_workers and training time. In the PPO case, none of the agents converge, this is likely related to #8.

**Comment by Josh-Joseph** [comment]
awesome. the cartpole results are definitely encouraging that this is mostly a tuning thing and not a rllib thing

were all these plots just for 1 run each or is the averaging over multiple runs in here?

**Comment by IsaacWolverton** [comment]
After running tests with a larger sample size I was able to confirm that increasing the number of workers does reduce the time required to train. Below are two images of DQN training on CartPole. The first is a graph of average reward at each iteration. The second is the printout of the final stats for the same run. Visually picture one shows that 3 workers trains faster than 0 workers, and picture two shows that on average agents using 3 workers converged more than twice as fast as agents using 0 workers. 

![ave_reward_19-38-29-12-13-2019](https://user-images.githubusercontent.com/31489037/70841692-758dc700-1dea-11ea-8a3b-c16f1f14d6a7.png)
![DQN_Cartpole_num_workers](https://user-images.githubusercontent.com/31489037/70841701-863e3d00-1dea-11ea-85c4-87785f755ddc.png)
